// <Project title> — generated by 3d-designer-skill
include <../../lib/gears.scad>
include <../../lib/hardware.scad>
part = "assembly";

// ---- parameters ----
size = [60, 40, 20];
wall = 2.4;
$fn = 64;

// ---- derived / checks ----
echo(str("CHECK size_x=", size[0], " wall=", wall, " ok=", wall >= 1.6));

module body() {
    difference() { cube(size); translate([wall, wall, wall]) cube(size - [2 * wall, 2 * wall, 0]); }
}

module assembly() { body(); }

if (part == "assembly") assembly();
else if (part == "body") body();
