// ============================================================================
//  Whatnot card-display turntable — slim, 12 V worm-gear-motor driven, 2–5 RPM
//  Parametric OpenSCAD model.  Generated by 3d-designer-skill.
//
//  Drive train:  JGY-370 12 V worm-gear motor (shaft up)  ->  17T printed pinion
//                ->  51T printed spur gear (3:1)  ->  8 mm steel rod (2x 608 bearings)
//                ->  hub  ->  display plate.
//  Electrical:   12 V barrel jack -> rocker switch (spin / hold) -> PWM speed
//                controller with panel knob -> motor.   See wiring.md.
//
//  Usage:   openscad -D 'part="base"' -o base.stl turntable.scad
//  Parts:   base, lid, plate, hub, spacer, gear, pinion, motor_strap, card_easel,
//           assembly (visual), exploded (visual)
//  Every dimension below is a parameter; z = 0 is the underside of the base.
// ============================================================================
include <../../lib/gears.scad>
include <../../lib/hardware.scad>

part = "assembly";
ghost_hardware = true;
interference_pair = -1;  // -1 = all pairs in the "interference" view, n = only pair n   // draw off-the-shelf parts transparent (%); false = solid, for cutaway renders

// ---------------- user-facing parameters ----------------
plate_d        = 210;   // display plate diameter (210 fits a 220 mm bed with a skirt)
plate_t        = 6;     // plate thickness
plate_lip_h    = 1.5;   // raised rim height (0 = flat plate)
plate_lip_w    = 4;     // raised rim width
plate_sections = 1;     // 1 = one piece, 2 = two halves (for small printers), glued + pinned

base_d   = 180;         // base diameter
wall     = 2.4;         // base wall thickness
floor_t  = 2.4;         // base floor thickness
lid_t    = 3;           // lid thickness

// gear train (module 1.5, 20 deg) -> 3:1.  15 RPM motor => 5 RPM plate at 100 % duty
gear_m       = 1.5;
pinion_teeth = 17;
gear_teeth   = 51;
gear_th      = 8;
gear_backlash = 0.15;   // printed gears: 0.1–0.2 mm

rod_d        = 8;       // 8 mm steel rod (or printed spindle, see docs)
rod_len      = 40;
rod_fit      = 0.15;    // extra bore clearance for printed parts sliding on the rod

fit_tight    = 0.15;    // press-fit allowance (bearing pockets)
fit_loose    = 0.4;     // sliding / drop-in allowance

m3_tap_d     = 2.6;     // self-tapping M3 hole
m3_clear_d   = 3.4;     // M3 clearance hole
m3_head_d    = 6.4;     // countersunk head diameter

pcb_bay_size = pcb_bay; // [60, 45, 18] from hardware.scad  (generic PWM module footprint)

// ---------------- derived layout (do not edit unless you know why) ----------------
base_r   = base_d / 2;
inner_r  = base_r - wall;
cd       = gear_center_distance(pinion_teeth, gear_teeth, gear_m);   // 51 mm
gear_or  = gear_outer_radius(gear_teeth, gear_m);                     // 39.75
pinion_or = gear_outer_radius(pinion_teeth, gear_m);                  // 14.25

gb_top    = floor_t + jgy_gb_h;          // motor gearbox top face
gear_z0   = gb_top + 1.5;                // gear plane bottom
gear_z1   = gear_z0 + gear_th;           // gear plane top
lid_z0    = gear_z1 + 1.5;               // underside of lid
lid_z1    = lid_z0 + lid_t;              // top of lid  == base height
shaft_tip = gb_top + jgy_shaft_len;      // motor shaft tip
need_relief = shaft_tip > lid_z0 - 0.5;  // motor shaft pokes into the lid -> relief hole

recess_depth = 5;                        // conical recess in the gear top for the lid bearing boss
recess_floor = gear_z1 - recess_depth;
lidboss_d    = 30;
lidboss_z0   = recess_floor + 0.5;
topbrg_z0    = lidboss_z0 + 1;           // 1 mm ledge under the top bearing
topbrg_z1    = topbrg_z0 + b608_w;

gearhub_d  = 16; gearhub_h = 8;
gearhub_z0 = gear_z0 - gearhub_h;
botbrg_z1  = gearhub_z0 - 0.5;
botbrg_z0  = botbrg_z1 - b608_w;
floortube_d = 30;

hub_disc_d  = 50; hub_disc_t = 3;
hub_boss_d  = 12; hub_boss_h = 3;        // rides on the top bearing inner race (OD 12.1)
hub_hex_af  = 22; hub_hex_h  = 6;        // hex boss above the plate carries the grub screw
plate_z0    = topbrg_z1 + hub_boss_h;    // underside of plate
plate_z1    = plate_z0 + plate_t;
rod_z0      = botbrg_z0 + 1;
rod_z1      = rod_z0 + rod_len;
total_h     = plate_z1 + hub_hex_h;

motor_pos   = [cd, 0, gb_top];           // motor shaft axis (x = centre distance)
motor_rot   = 0;                         // motor can points +Y (tangential) to keep the base small
strap_y     = jgy_gb_len - jgy_shaft_from_end + 14;   // strap over the can, 14 mm past the gearbox
strap_boss_dx = jgy_body_d / 2 + wall + 3.5;

pcb_center  = [-52, 0];                  // PWM module bay, opposite the motor
lid_screw_r = inner_r - 3.5;
lid_screw_angles = [30, 90, 150, 210, 270, 330];

switch_pos  = [-25, 0];   // x, and z-centre handled below (front wall = -Y)
pot_x       = 25;
jack_x      = -40;        // rear wall (+Y)
panel_zc    = floor_t + 17;

$fn = 96;

// ---------- design checks echoed for the inspector ----------
echo(str("CHECK base_height=", lid_z1, " total_height=", total_h, " plate_d=", plate_d, " base_d=", base_d));
echo(str("CHECK center_distance=", cd, " gear_od=", 2 * gear_or, " pinion_od=", 2 * pinion_or, " ratio=", gear_teeth / pinion_teeth));
echo(str("CHECK motor_shaft_tip=", shaft_tip, " lid_z0=", lid_z0, " relief=", need_relief));
echo(str("CHECK rod_span_lo=", rod_z0, " rod_span_hi=", rod_z1, " hub_hex_top=", total_h));
motor_far = sqrt(pow(cd + jgy_body_d / 2, 2) + pow(jgy_gb_len - jgy_shaft_from_end + jgy_body_len + jgy_term_len, 2));
echo(str("CHECK motor_far_radius=", motor_far, " inner_r=", inner_r, " ok=", motor_far < inner_r - 1));
pcb_far = sqrt(pow(abs(pcb_center[0]) + pcb_bay_size[1] / 2 + 3, 2) + pow(pcb_bay_size[0] / 2 + 3, 2));
echo(str("CHECK pcb_far_radius=", pcb_far, " ok=", pcb_far < inner_r - 0.5));

// ============================================================================
//  PARTS
// ============================================================================

module m3_boss(h, d = 7) { difference() { cylinder(d = d, h = h); translate([0, 0, h - 8]) cylinder(d = m3_tap_d, h = 9, $fn = 20); } }

module base() {
    difference() {
        union() {
            // shell
            difference() {
                cylinder(r = base_r, h = lid_z0);
                translate([0, 0, floor_t]) cylinder(r = inner_r, h = lid_z0);
            }
            // centre spindle tube (bottom bearing)
            cylinder(d = floortube_d, h = botbrg_z1);
            // lid screw bosses
            for (a = lid_screw_angles) rotate(a) translate([lid_screw_r, 0, 0]) m3_boss(lid_z0);
            // motor cradle
            translate(motor_pos) rotate(motor_rot) motor_cradle();
            // PWM module bay walls
            translate([pcb_center[0], pcb_center[1], 0]) pcb_bay_walls();
        }
        // bottom bearing pocket + inner-race relief
        translate([0, 0, botbrg_z0]) cylinder(d = b608_od + fit_tight, h = 20);
        translate([0, 0, botbrg_z0 - 1]) cylinder(d = 18, h = 2);
        // front panel cutouts: rocker switch + potentiometer  (front = -Y)
        translate([switch_pos[0], -base_r, panel_zc]) cube([kcd1_cut[0], 3 * wall, kcd1_cut[1]], center = true);
        translate([pot_x, -base_r, panel_zc]) rotate([90, 0, 0]) { cylinder(d = pot_hole_d, h = 3 * wall, center = true);
            translate([pot_hole_d / 2 + pot_key_w / 2, 0, 0]) cube([pot_key_w, 1.6, 3 * wall], center = true); }
        // rear: DC barrel jack
        translate([jack_x, base_r, panel_zc]) rotate([90, 0, 0]) cylinder(d = jack_hole_d, h = 3 * wall, center = true);
        // rubber-foot recesses
        for (a = [45, 135, 225, 315]) rotate(a) translate([base_r - 14, 0, -0.01]) cylinder(d = 12.4, h = 0.8);
        // motor envelope (clears the cradle where it wraps the gearbox / can)
        translate(motor_pos) rotate(motor_rot) jgy370(clearance = 0.3);
    }
}

module motor_cradle() {
    // gearbox corner ribs (gearbox is a box: x ±w/2, y -shaft_from_end .. len-shaft_from_end, z -gb_h .. 0)
    hx = jgy_gb_w / 2 + 0.3; y0 = -jgy_shaft_from_end - 0.3; y1 = jgy_gb_len - jgy_shaft_from_end + 0.3;
    rib_h = 12; rib_t = 2.4; rib_l = 10;
    translate([0, 0, -jgy_gb_h]) {
        for (sx = [-1, 1]) for (sy = [0, 1]) {
            yy = sy == 0 ? y0 : y1;
            translate([sx * hx + (sx > 0 ? 0 : -rib_t), sy == 0 ? yy - rib_t : yy, 0]) cube([rib_t, rib_t, rib_h]);
            translate([sx * hx + (sx > 0 ? 0 : -rib_t), sy == 0 ? yy : yy - rib_l, 0]) cube([rib_t, rib_l, rib_h]);
            translate([sx > 0 ? hx - rib_l : -hx, sy == 0 ? yy - rib_t : yy, 0]) cube([rib_l, rib_t, rib_h]);
        }
        // saddle under the motor can (can axis is at gearbox mid-height)
        translate([0, strap_y, 0]) difference() {
            translate([-(jgy_body_d / 2 + wall + 2), -5, 0]) cube([jgy_body_d + 2 * wall + 4, 10, jgy_gb_h / 2]);
            translate([0, -6, jgy_gb_h / 2]) rotate([-90, 0, 0]) cylinder(d = jgy_body_d + 0.6, h = 12);
        }
        // strap screw bosses either side of the can
        for (sx = [-1, 1]) translate([sx * strap_boss_dx, strap_y, 0]) m3_boss(jgy_gb_h / 2, d = 7);
    }
}

module motor_strap() {
    // half-ring that clamps the motor can; screws into the two cradle bosses
    r_in = jgy_body_d / 2 + 0.3; t = 2.4; w = 8;
    difference() {
        union() {
            rotate([90, 0, 0]) cylinder(r = r_in + t, h = w, center = true);
            for (sx = [-1, 1]) translate([sx * strap_boss_dx, 0, 0]) hull() {
                cylinder(d = 7, h = t); translate([-sx * 4, 0, 0]) cylinder(d = 7, h = t); }
            translate([-(r_in + t), -w / 2, 0]) cube([2 * (r_in + t), w, t]);
        }
        rotate([90, 0, 0]) cylinder(r = r_in, h = w + 2, center = true);
        translate([-50, -50, -50]) cube([100, 100, 50]);   // keep the upper half only
        for (sx = [-1, 1]) translate([sx * strap_boss_dx, 0, -1]) cylinder(d = m3_clear_d, h = 10, $fn = 20);
    }
}

module pcb_bay_walls() {
    L = pcb_bay_size[0]; W = pcb_bay_size[1]; h = 6; t = 2;
    difference() {
        translate([-(W / 2 + t), -(L / 2 + t), 0]) cube([W + 2 * t, L + 2 * t, h]);
        translate([-W / 2, -L / 2, -1]) cube([W, L, h + 2]);
        // wire notches
        for (s = [-1, 1]) translate([s * (W / 2 + t), 0, h - 2]) cube([2 * t + 1, 8, 5], center = true);
    }
}

module lid() {
    difference() {
        union() {
            translate([0, 0, lid_z0]) cylinder(r = base_r, h = lid_t);
            // locating lip that drops inside the wall
            translate([0, 0, lid_z0 - 2]) difference() {
                cylinder(r = inner_r - fit_loose / 2, h = 2);
                translate([0, 0, -1]) cylinder(r = inner_r - fit_loose / 2 - 2, h = 4);
                for (a = lid_screw_angles) rotate(a) translate([lid_screw_r, 0, -1]) cylinder(d = 7 + fit_loose, h = 4);   // notch around each boss
            }
            // bearing boss hanging into the gear recess
            translate([0, 0, lidboss_z0]) cylinder(d = lidboss_d, h = lid_z0 - lidboss_z0 + 0.01);
        }
        // top bearing pocket (open to the top, ledge below)
        translate([0, 0, topbrg_z0]) cylinder(d = b608_od + fit_tight, h = 20);
        translate([0, 0, lidboss_z0 - 1]) cylinder(d = 18, h = 5);
        // lid screws (countersunk)
        for (a = lid_screw_angles) rotate(a) translate([lid_screw_r, 0, lid_z0 - 1]) {
            cylinder(d = m3_clear_d, h = 10, $fn = 20);
            translate([0, 0, 1 + lid_t - 1.8]) cylinder(d1 = m3_clear_d, d2 = m3_head_d, h = 1.8, $fn = 24);
        }
        // motor shaft relief
        if (need_relief) translate([motor_pos[0], motor_pos[1], lid_z0 - 1]) cylinder(d = 10, h = 10);
        // small vent slots over the motor
        for (i = [-1, 0, 1]) translate([motor_pos[0] + i * 6, motor_pos[1] + 32, lid_z0 - 1]) cube([2, 20, 10], center = true);
    }
}

module spur_gear() {
    translate([0, 0, gearhub_z0]) difference() {
        union() {
            translate([0, 0, gearhub_h]) involute_gear(gear_teeth, gear_m, gear_th, backlash = gear_backlash, bore = 0);
            cylinder(d = gearhub_d, h = gearhub_h + 0.01);
        }
        translate([0, 0, -1]) cylinder(d = rod_d + rod_fit, h = gearhub_h + gear_th + 2, $fn = 48);
        // lid-boss recess in the top face
        translate([0, 0, gearhub_h + gear_th - recess_depth]) cylinder(d1 = lidboss_d, d2 = lidboss_d + 2 * (recess_depth + 1), h = recess_depth + 1);  // 45° wall, 0.5 mm radial clearance at the boss corner
        // radial grub screw through the hub
        translate([0, 0, gearhub_h / 2]) rotate([0, 90, 0]) cylinder(d = m3_tap_d, h = gearhub_d, $fn = 20);
    }
}

module pinion() {
    translate([motor_pos[0], motor_pos[1], gear_z0])
        involute_gear(pinion_teeth, gear_m, gear_th, backlash = gear_backlash, bore = jgy_shaft_d + 0.1, bore_flat = jgy_shaft_flat + 0.1);
}

module spacer() {
    // rides on the top bearing inner race (OD 12.1) through the lid's 18 mm hole; carries the plate weight
    translate([0, 0, topbrg_z1]) difference() { cylinder(d = hub_boss_d, h = hub_boss_h); translate([0, 0, -1]) cylinder(d = rod_d + rod_fit, h = 10, $fn = 48); }
}

module hub() {
    difference() {
        union() {
            translate([0, 0, plate_z0]) cylinder(d = hub_disc_d, h = hub_disc_t);
            translate([0, 0, plate_z0]) cylinder(d = hub_hex_af / cos(30), h = plate_t + hub_hex_h, $fn = 6);
        }
        translate([0, 0, plate_z0 - 1]) cylinder(d = rod_d + rod_fit, h = 60, $fn = 48);
        // grub screw in the hex boss, above the plate
        translate([0, 0, plate_z1 + hub_hex_h / 2]) rotate([0, 90, 0]) cylinder(d = m3_tap_d, h = 30, $fn = 20);
        // plate fixing screws (self-tapping into the disc)
        for (a = [0, 120, 240]) rotate(a) translate([18, 0, plate_z0 - 1]) cylinder(d = m3_tap_d, h = 10, $fn = 20);
    }
}

module plate_body() {
    // one revolved profile (body + rim + top chamfer) so the mesh is manifold by construction
    R = plate_d / 2; c = 0.6; lw = plate_lip_h > 0 ? plate_lip_w : 0;
    profile = plate_lip_h > 0
        ? [[0, 0], [R, 0], [R, plate_t + plate_lip_h - c], [R - c, plate_t + plate_lip_h], [R - lw, plate_t + plate_lip_h], [R - lw, plate_t], [0, plate_t]]
        : [[0, 0], [R, 0], [R, plate_t - c], [R - c, plate_t], [0, plate_t]];
    difference() {
        translate([0, 0, plate_z0]) rotate_extrude($fn = 180) polygon(profile);
        // hex hole for the hub boss + underside pocket for the hub disc
        translate([0, 0, plate_z0 - 1]) cylinder(d = (hub_hex_af + fit_loose) / cos(30), h = 20, $fn = 6);
        translate([0, 0, plate_z0 - 1]) cylinder(d = hub_disc_d + fit_loose, h = hub_disc_t + 1);
        for (a = [0, 120, 240]) rotate(a) translate([18, 0, plate_z0 - 1]) {
            cylinder(d = m3_clear_d, h = 20, $fn = 20);
            translate([0, 0, 1 + plate_t - 1.8]) cylinder(d1 = m3_clear_d, d2 = m3_head_d, h = 1.81, $fn = 24);
        }
    }
}

module plate(half = 0) {
    if (plate_sections == 1) plate_body();
    else {
        // two halves joined on the Y axis, 3 mm pins + glue
        difference() {
            intersection() {
                plate_body();
                translate([half == 0 ? -plate_d : 0.15, -plate_d, 0]) cube([plate_d - 0.15, 2 * plate_d, 100]);
            }
            for (y = [-plate_d / 2 + 20, -40, 40, plate_d / 2 - 20])
                translate([0, y, plate_z0 + plate_t / 2]) rotate([0, 90, 0]) cylinder(d = 3.2, h = 24, center = true, $fn = 20);
        }
    }
}

module card_easel() {
    // sits on the plate; holds a 3x4" toploader (77 x 102 x ~2 mm) tilted 15 degrees back
    w = 90; d = 34; h = 12; tilt = 15;
    difference() {
        hull() { translate([-w / 2, -d / 2, 0]) cube([w, d, 2]); translate([-w / 2, -d / 2 + 6, 0]) cube([w, d - 6, h]); }
        translate([0, 2, h]) rotate([tilt, 0, 0]) translate([-42, -2.2, -9]) cube([84, 4.4, 20]);
        translate([0, -8, h]) rotate([tilt, 0, 0]) translate([-42, -1.1, -9]) cube([84, 2.2, 20]);   // second slot for a raw sleeve
    }
}

// ============================================================================
//  ASSEMBLY VIEWS
// ============================================================================
module hardware_ghosts() {
    if (ghost_hardware) %hardware_solid(); else hardware_solid();
}
module hardware_solid() {
    color("DimGray") translate(motor_pos) rotate(motor_rot) jgy370();
    color("Silver") translate([0, 0, botbrg_z0]) bearing608();
    color("Silver") translate([0, 0, topbrg_z0]) bearing608();
    color("Silver") translate([0, 0, rod_z0]) cylinder(d = rod_d, h = rod_len, $fn = 32);
}

module assembly(explode = 0) {
    e = explode;
    color("SlateGray") base();
    color("SlateGray") translate(motor_pos) translate([0, strap_y, -jgy_gb_h / 2 + e * 0.6]) motor_strap();
    color("Gold") translate([0, 0, e * 0.3]) spur_gear();
    color("Gold") translate([0, 0, e * 0.3]) pinion();
    color("LightSteelBlue", 0.85) translate([0, 0, e]) lid();
    color("Tomato") translate([0, 0, e * 1.4]) spacer();
    color("Tomato") translate([0, 0, e * 1.6]) hub();
    color("WhiteSmoke") translate([0, 0, e * 2]) { plate(0); if (plate_sections == 2) plate(1); }
    color("WhiteSmoke") translate([0, 40, plate_z1 + plate_lip_h + e * 2.4]) card_easel();
    hardware_ghosts();
}

// ============================================================================
//  PART SELECTOR — printable parts are re-oriented flat on the bed
// ============================================================================
if (part == "assembly") assembly();
else if (part == "exploded") assembly(explode = 25);
else if (part == "section") difference() { assembly(); translate([-200, 0, -1]) cube([400, 400, 100]); }   // cut on the XZ plane through the motor
else if (part == "gears") { spur_gear(); pinion(); }   // mesh check view
else if (part == "interference") {                       // must compile to an EMPTY solid (inspector checks volume ~ 0)
    pairs = [
        ["gear/pinion",  0], ["gear/lid", 1], ["gear/base", 2], ["pinion/lid", 3], ["pinion/base", 4],
        ["base/motor", 5], ["lid/motor", 6], ["lid/hub", 7], ["lid/plate", 8], ["base/lid", 9], ["topbearing/hub", 10]];
    for (i = [0 : len(pairs) - 1]) if (interference_pair < 0 || interference_pair == i) {
        echo(str("INTERFERENCE pair ", i, " = ", pairs[i][0]));
        if (i == 0) intersection() { spur_gear(); pinion(); }
        if (i == 1) intersection() { spur_gear(); lid(); }
        if (i == 2) intersection() { spur_gear(); base(); }
        if (i == 3) intersection() { pinion(); lid(); }
        if (i == 4) intersection() { pinion(); base(); }
        if (i == 5) intersection() { base(); translate(motor_pos) rotate(motor_rot) jgy370(); }
        if (i == 6) intersection() { lid(); translate(motor_pos) rotate(motor_rot) jgy370(); }
        if (i == 7) intersection() { lid(); hub(); }
        if (i == 8) intersection() { lid(); plate(0); }
        if (i == 9) intersection() { base(); lid(); }
        if (i == 10) intersection() { translate([0, 0, topbrg_z0]) bearing608(); hub(); }
    }
}
else if (part == "base") base();
else if (part == "lid") translate([0, 0, lid_z1]) mirror([0, 0, 1]) lid();          // print top face down
else if (part == "gear") translate([0, 0, gear_z1]) mirror([0, 0, 1]) spur_gear();  // print teeth face down, hub up
else if (part == "pinion") translate([-motor_pos[0], -motor_pos[1], -gear_z0]) pinion();
else if (part == "hub") translate([0, 0, -plate_z0]) hub();                         // disc flat on the bed, hex boss up
else if (part == "spacer") translate([0, 0, -topbrg_z1]) spacer();
else if (part == "plate") translate([0, 0, -plate_z0]) plate(0);
else if (part == "plate_half_b") translate([0, 0, -plate_z0]) plate(1);
else if (part == "motor_strap") rotate([90, 0, 0]) translate([0, 4, 0]) motor_strap();   // on its side: arch prints as a 2-D profile
else if (part == "card_easel") card_easel();
